### scorep_env

In [1]:
%%scorep_env
SCOREP_ENABLE_TRACING=1
SCOREP_ENABLE_PROFILING=0
SCOREP_TOTAL_MEMORY=3g
SCOREP_EXPERIMENT_DIRECTORY=test_kernel_tmp/scorep-traces

Score-P environment set successfully: {'SCOREP_ENABLE_TRACING': '1', 'SCOREP_ENABLE_PROFILING': '0', 'SCOREP_TOTAL_MEMORY': '3g', 'SCOREP_EXPERIMENT_DIRECTORY': 'test_kernel_tmp/scorep-traces'}

### scorep_pythonargs

In [2]:
%%scorep_python_binding_arguments
--noinstrumenter

Score-P Python binding arguments set successfully: ['--noinstrumenter']

### ipykernel_exec

In [3]:
%%bash
export MY_ENV_VAR=1234
echo MY_ENV_VAR=$MY_ENV_VAR

MY_ENV_VAR=1234


In [4]:
a = 5
b = 10

In [5]:
print('a + b =', a + b)

a + b = 15


### scorep_exec

In [6]:
%%serializer_settings
dill
memory

Serializer set to 'dill', mode set to 'memory'.

In [7]:
%%execute_with_scorep
import scorep
with scorep.instrumenter.enable():
    print('a - b =', a - b)

a - b = -5
Instrumentation results can be found in test_kernel_tmp/scorep-traces

In [8]:
%%serializer_settings
dill
disk

Serializer set to 'dill', mode set to 'disk'.

In [9]:
%%execute_with_scorep
import scorep
with scorep.instrumenter.enable():
    print('a - b =', a - b)

a - b = -5
Instrumentation results can be found in test_kernel_tmp/scorep-traces

In [10]:
%%serializer_settings
cloudpickle
memory

Serializer set to 'cloudpickle', mode set to 'memory'.

In [11]:
%%execute_with_scorep
import scorep
with scorep.instrumenter.enable():
    print('a - b =', a - b)

a - b = -5
Instrumentation results can be found in test_kernel_tmp/scorep-traces

In [12]:
%%serializer_settings
cloudpickle
disk

Serializer set to 'cloudpickle', mode set to 'disk'.

In [13]:
%%execute_with_scorep
import scorep
with scorep.instrumenter.enable():
    print('a - b =', a - b)

a - b = -5
Instrumentation results can be found in test_kernel_tmp/scorep-traces

### persistence

In [14]:
%env JUPYTER_VAR=JUPYTER

env: JUPYTER_VAR=JUPYTER


In [15]:
import numpy as np
def f(x):
    return x**2
a_vec = np.arange(a)
b_vec = np.arange(a, b)

import sys
sys.path.append('/new/jupyter/path')

In [16]:
%%execute_with_scorep
import pandas as pd
def g(x):
    return np.log2(x)
with scorep.instrumenter.enable():
    c_mtx = np.outer(a_vec, b_vec)
print('Inner product of a_vec and b_vec =', np.dot(a_vec, b_vec))
print('f(4) =', f(4))

import os
import sys
print('JUPYTER_VAR =', os.environ['JUPYTER_VAR'])
if '/new/jupyter/path' in sys.path:
    print("'/new/jupyter/path' found in sys.path")

os.environ['SUBPROCESS_VAR'] = 'SUBPROCESS'
sys.path.append('/new/subprocess/path')

Inner product of a_vec and b_vec = 80
f(4) = 16
JUPYTER_VAR = JUPYTER
'/new/jupyter/path' found in sys.path
Instrumentation results can be found in test_kernel_tmp/scorep-traces

In [17]:
print('Outer product of a_vec and b_vec =\n', c_mtx)
print('g(16) =', g(16))

Outer product of a_vec and b_vec =
 [[ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [10 12 14 16 18]
 [15 18 21 24 27]
 [20 24 28 32 36]]
g(16) = 4.0


In [18]:
df = pd.DataFrame(np.vstack([a_vec, b_vec]).T, columns=['a', 'b'])
df['a*b'] = df['a'] * df['b']
print(df['a*b'])

0     0
1     6
2    14
3    24
4    36
Name: a*b, dtype: int64


In [19]:
%env SUBPROCESS_VAR

'SUBPROCESS'

In [ ]:
if '/new/subprocess/path' in sys.path:
    print("'/new/subprocess/path' found in sys.path")

### multicell

In [ ]:
%%enable_multicellmode

In [ ]:
c = np.sum(c_mtx)

In [ ]:
%%abort_multicellmode

In [ ]:
%%enable_multicellmode

In [ ]:
with scorep.instrumenter.enable():
    c = np.sum(c_mtx)
c_vec = np.arange(b, c)

In [ ]:
print('c =', c)
print('Sum(c_vec) =', c_vec.sum())

In [ ]:
%%finalize_multicellmode

### writemode

In [ ]:
%%start_writefile test_kernel_tmp/my_jupyter_to_script

In [ ]:
%%scorep_env
SCOREP_ENABLE_TRACING=1
SCOREP_ENABLE_PROFILING=0
SCOREP_TOTAL_MEMORY=3g
SCOREP_EXPERIMENT_DIRECTORY=test_kernel_tmp/scorep-traces

In [ ]:
%%scorep_python_binding_arguments
--noinstrumenter

In [ ]:
import numpy as np
a = 5
b = 10
a_vec = np.arange(a)
b_vec =  np.arange(a, b)
print('a + b =', a + b)

In [ ]:
%%execute_with_scorep
import scorep
print('a - b =', a - b)
with scorep.instrumenter.enable():
    c_mtx = np.outer(a_vec, b_vec)

In [ ]:
%%enable_multicellmode

In [ ]:
c = np.sum(c_mtx)

In [ ]:
with scorep.instrumenter.enable():
    c = np.sum(c_mtx)
c_vec = np.arange(b, c)

In [ ]:
print('c =', c)
print('Sum(c_vec) =', c_vec.sum())

In [ ]:
%%finalize_multicellmode

In [ ]:
%%end_writefile

In [ ]:
%%bash
chmod u+x test_kernel_tmp/my_jupyter_to_script_run.sh
./test_kernel_tmp/my_jupyter_to_script_run.sh